Adding support to produce avro encoded messages
birdayz/kaf pull request #192
Opened 2022-04-21 01:59 UTC by fabiojmendes

Turns out most of the heavy lifting was already done by the schemaCache implementation. If you think this approach is fine I would like to add support for avro keys as well.

Fixes #181

2022-04-21 14:38 UTC, birdayz requested changes

2022-04-21 14:38 UTC, birdayz commented on cmd/kaf/produce.go
> +	produceCmd.Flags().IntVarP(&schemaID, "schema-id", "", -1, "Value schema id for avro messsage encoding")
what about changing this to --avro-schema-id ? i think this is more in line with other flags like --proto-*

2022-04-21 17:31 UTC, fabiojmendes commented
No problem! I love the cli kaf provides. It is much more intuitive and easy to use compared to the default kafka-console-consumer/producer. But avro is a must have for me :)

I'll move on to the avro key support and see how that looks like. Do you think it would make sense to create an Interface for encoders? That way we can streamline the code on the producer side instead of having a if statement to check for each case.

2022-04-22 19:10 UTC, birdayz commented
I agree with the interface. We would have two implementations already: protobuf and avro. If those two match the interface, we can have good confidence that the interface is well designed.

2022-04-22 19:11 UTC, merged

2022-04-22 19:33 UTC, eshepelyuk commented
@fabiojmendes @birdayz can you plz provide detailled examples how to use it ?
I am not sure this code can close #181

2022-04-22 20:54 UTC, fabiojmendes commented
@eshepelyuk you need a json message that matches your avro schema and the `avro-schema-id` flag to the corresponding schema in schema-registry . Note that you also need to have the schema-registry configured for this to work.

Here's an example
```
echo '{"id":1,"name":"User"}' | kaf produce --avro-schema-id 3 some.topic
```

My schema looks like this:
```json
{
  "type": "record",
  "name": "user",
  "fields": [
    { "name": "id", "type": "int" },
    { "name": "name", "type": "string" }
  ]
}
```

If you would like to use a file, you can just cat the file into this pipeline using one record per line:
```
cat file.json | kaf produce --avro-schema-id 3 some.topic
```

2022-04-23 03:09 UTC, eshepelyuk commented
Thnx !
Are you planning a new release with this feature included soon ?

2022-04-23 06:43 UTC, birdayz commented
i published a fresh release.